# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/kuscum/usr/usr/local/bin/cmake

# The command to remove a file.
RM = /home/kuscum/usr/usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kuscum/workspace/TAS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kuscum/workspace/TAS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/.fs3-home1/kuscum/usr/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/.fs3-home1/kuscum/usr/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kuscum/workspace/TAS/CMakeFiles /home/kuscum/workspace/TAS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kuscum/workspace/TAS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FASD

# Build rule for target.
FASD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FASD
.PHONY : FASD

# fast build rule for target.
FASD/fast:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/build
.PHONY : FASD/fast

measurements/run_applications.o: measurements/run_applications.cpp.o

.PHONY : measurements/run_applications.o

# target to build an object file
measurements/run_applications.cpp.o:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/measurements/run_applications.cpp.o
.PHONY : measurements/run_applications.cpp.o

measurements/run_applications.i: measurements/run_applications.cpp.i

.PHONY : measurements/run_applications.i

# target to preprocess a source file
measurements/run_applications.cpp.i:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/measurements/run_applications.cpp.i
.PHONY : measurements/run_applications.cpp.i

measurements/run_applications.s: measurements/run_applications.cpp.s

.PHONY : measurements/run_applications.s

# target to generate assembly for a file
measurements/run_applications.cpp.s:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/measurements/run_applications.cpp.s
.PHONY : measurements/run_applications.cpp.s

src/examples/gameOfLife.o: src/examples/gameOfLife.cpp.o

.PHONY : src/examples/gameOfLife.o

# target to build an object file
src/examples/gameOfLife.cpp.o:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/gameOfLife.cpp.o
.PHONY : src/examples/gameOfLife.cpp.o

src/examples/gameOfLife.i: src/examples/gameOfLife.cpp.i

.PHONY : src/examples/gameOfLife.i

# target to preprocess a source file
src/examples/gameOfLife.cpp.i:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/gameOfLife.cpp.i
.PHONY : src/examples/gameOfLife.cpp.i

src/examples/gameOfLife.s: src/examples/gameOfLife.cpp.s

.PHONY : src/examples/gameOfLife.s

# target to generate assembly for a file
src/examples/gameOfLife.cpp.s:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/gameOfLife.cpp.s
.PHONY : src/examples/gameOfLife.cpp.s

src/examples/jacobian.o: src/examples/jacobian.cpp.o

.PHONY : src/examples/jacobian.o

# target to build an object file
src/examples/jacobian.cpp.o:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/jacobian.cpp.o
.PHONY : src/examples/jacobian.cpp.o

src/examples/jacobian.i: src/examples/jacobian.cpp.i

.PHONY : src/examples/jacobian.i

# target to preprocess a source file
src/examples/jacobian.cpp.i:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/jacobian.cpp.i
.PHONY : src/examples/jacobian.cpp.i

src/examples/jacobian.s: src/examples/jacobian.cpp.s

.PHONY : src/examples/jacobian.s

# target to generate assembly for a file
src/examples/jacobian.cpp.s:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/jacobian.cpp.s
.PHONY : src/examples/jacobian.cpp.s

src/examples/sparseMatrixMultiplication.o: src/examples/sparseMatrixMultiplication.cpp.o

.PHONY : src/examples/sparseMatrixMultiplication.o

# target to build an object file
src/examples/sparseMatrixMultiplication.cpp.o:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/sparseMatrixMultiplication.cpp.o
.PHONY : src/examples/sparseMatrixMultiplication.cpp.o

src/examples/sparseMatrixMultiplication.i: src/examples/sparseMatrixMultiplication.cpp.i

.PHONY : src/examples/sparseMatrixMultiplication.i

# target to preprocess a source file
src/examples/sparseMatrixMultiplication.cpp.i:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/sparseMatrixMultiplication.cpp.i
.PHONY : src/examples/sparseMatrixMultiplication.cpp.i

src/examples/sparseMatrixMultiplication.s: src/examples/sparseMatrixMultiplication.cpp.s

.PHONY : src/examples/sparseMatrixMultiplication.s

# target to generate assembly for a file
src/examples/sparseMatrixMultiplication.cpp.s:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/sparseMatrixMultiplication.cpp.s
.PHONY : src/examples/sparseMatrixMultiplication.cpp.s

src/examples/v2_SparseM.o: src/examples/v2_SparseM.cpp.o

.PHONY : src/examples/v2_SparseM.o

# target to build an object file
src/examples/v2_SparseM.cpp.o:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/v2_SparseM.cpp.o
.PHONY : src/examples/v2_SparseM.cpp.o

src/examples/v2_SparseM.i: src/examples/v2_SparseM.cpp.i

.PHONY : src/examples/v2_SparseM.i

# target to preprocess a source file
src/examples/v2_SparseM.cpp.i:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/v2_SparseM.cpp.i
.PHONY : src/examples/v2_SparseM.cpp.i

src/examples/v2_SparseM.s: src/examples/v2_SparseM.cpp.s

.PHONY : src/examples/v2_SparseM.s

# target to generate assembly for a file
src/examples/v2_SparseM.cpp.s:
	$(MAKE) -f CMakeFiles/FASD.dir/build.make CMakeFiles/FASD.dir/src/examples/v2_SparseM.cpp.s
.PHONY : src/examples/v2_SparseM.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FASD"
	@echo "... measurements/run_applications.o"
	@echo "... measurements/run_applications.i"
	@echo "... measurements/run_applications.s"
	@echo "... src/examples/gameOfLife.o"
	@echo "... src/examples/gameOfLife.i"
	@echo "... src/examples/gameOfLife.s"
	@echo "... src/examples/jacobian.o"
	@echo "... src/examples/jacobian.i"
	@echo "... src/examples/jacobian.s"
	@echo "... src/examples/sparseMatrixMultiplication.o"
	@echo "... src/examples/sparseMatrixMultiplication.i"
	@echo "... src/examples/sparseMatrixMultiplication.s"
	@echo "... src/examples/v2_SparseM.o"
	@echo "... src/examples/v2_SparseM.i"
	@echo "... src/examples/v2_SparseM.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

