#!/bin/bash
#
# This is a script file for applications built using the TxHPC framwework,
# for shared access to Gen-Z-style byte addressable shared memory across nodes
# (as in The Machine).
# See: http://genzconsortium.org/
#
#    [HPE copyright notice]
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    As an exception, the copyright holders of this Library grant you permission to
#   (i) compile an #Application with the Library, and
#    (ii) distribute the Application containing code generated by the Library and    
#    added to the Application during this compilation process under terms of your
#    choice, provided you also meet the terms and conditions of the Application license.

k=16384
j=2
l=1
while [ $k != 2199023255552 ]
do
	./r6_emu_dram $k 8 11 2 $j 1 1 1024 0 > results/r6DRAM_nf/"r6_log_$k"
	#cp /proc/`pidof r6_emu`/status results/"mem_$k"
	echo `pidof r6_emu` 
	k=$(( k * 2 ))
	if [ $k = 32768 ]; then
		j=$(( j * 2 ))
	fi
	if [ $k = 65536 ]; then
		j=$(( j * 2 ))
	fi
	if [ $k = 131072 ]; then
		j=$(( j * 2 ))
	fi
	if [ $k = 4194304 ]; then
		j=$(( j * 2 ))
	fi
	if [ $k = 33554432 ]; then
		j=$(( j * 2 ))
	fi
	if [ $k = 268435456 ]; then
		j=$(( j * 2 ))
	fi
	if [ $k = 10737441824 ]; then
		j=$(( j * 2 ))
	fi
	if [ $k = 2147483648 ]; then
		j=$(( j * 2 ))
	fi
	if [ $k = 4294967296 ]; then
        	j=$(( j * 2 ))      
	fi                
	if [ $k = 17179869184 ]; then
                j=$(( j * 2 ))
        fi
        if [ $k = 34359738368 ]; then
                j=$(( j * 2 ))
        fi          
	if [ $k = 68719476736 ]; then
        	j=$(( j * 2 ))       
 	fi                           
 	if [ $k = 137438953472 ]; then
        	j=$(( j * 2 ))       
 	fi                    
	if [ $k = 274877906944 ]; then
                j=$(( j * 2 ))
        fi
        if [ $k = 549755813888 ]; then
                j=$(( j * 2 ))
        fi
        if [ $k = 1099511627776 ]; then
                j=$(( j * 2 ))
        fi       
done
