//
// Created by kuscum on 7/11/16.
//
/*
This is a the header file for applications built using the TxHPC framwework, for shared access to Gen-Z-style byte addressable shared memory across nodes (as in The Machine).
See: http://genzconsortium.org/

    [HPE copyright notice]

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    As an exception, the copyright holders of this Library grant you permission to (i) compile an Application with the Library, and
    (ii) distribute the Application containing code generated by the Library and    
    added to the Application during this compilation process under terms of your choice, provided you also meet the terms and conditions of the Application license.

 */

#ifndef TxHPC_H
#define TxHPC_H

extern "C" {
#include "include/StencilForTxHPC/TxHPC4TM/raid6/include/r6_utils.h"
}

#include "include/portable_pointer/portable_pointer.h"
#include "include/portable_pointer/catalogue.h"
#include "include/StencilForTxHPC/physis_api.h"

#endif //TxHPC_H

